# Generated by Django 5.0.7 on 2024-08-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("thread_id", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("documento", models.CharField(max_length=50)),
                ("producto", models.CharField(max_length=255)),
                ("lote", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "file_manager_documentrequest",
            },
        ),
    ]
