# Generated by Django 5.0.7 on 2024-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("File_Manager", "0002_alter_documentrequest_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="producto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
