# Generated by Django 5.0.7 on 2024-08-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("File_Manager", "0004_documentrequest_user_interaction_and_more"),
        ("Module_Manager", "0003_userinteraction_task_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentrequest",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="link",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="user_interaction",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_requests",
                to="Module_Manager.userinteraction",
            ),
        ),
        migrations.AlterModelTable(
            name="documentrequest",
            table="file_manager_documentrequest",
        ),
    ]
