# Generated by Django 5.0.7 on 2024-08-27 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("File_Manager", "0006_rename_created_at_documentrequest_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentrequest",
            name="user_interaction",
        ),
        migrations.AlterModelTable(
            name="documentrequest",
            table="file_manager_documentrequest",
        ),
    ]
