# Generated by Django 5.0.7 on 2024-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Module_Manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="user_id",
            field=models.CharField(max_length=255),
        ),
    ]
