# Generated by Django 5.0.7 on 2024-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Module_Manager", "0003_userinteraction_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
