# Generated by Django 5.0.7 on 2024-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Module_Manager", "0004_alter_whatsappuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinteraction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
