# Generated by Django 5.0.7 on 2024-09-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Module_Manager", "0007_userinteraction_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinteraction",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
