# Generated by Django 5.0.7 on 2025-01-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Module_Manager", "0008_alter_userinteraction_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="language",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
