# Generated by Django 5.0.7 on 2025-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("surname", models.CharField(blank=True, default="", max_length=100)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("how_did_you_know_about_us", models.TextField(blank=True, default="")),
                (
                    "level_of_knowledge_of_products",
                    models.TextField(blank=True, default=""),
                ),
                ("additional_comments", models.TextField(blank=True, default="")),
            ],
        ),
    ]
