# Generated by Django 5.0.7 on 2025-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Form_Manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdetails",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
