name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull mate7/deploy:latest
    - name: Delete Old docker container
      run: sudo docker rm -f deploy-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8001:8001 --name deploy-container mate7/deploy