name: Deploy to EC2

on:
  push:
    branches:
      - deployment

env:
  PROJECT_PATH: /home/ubuntu/Agente_Terry

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Add host to known_hosts
        run: ssh-keyscan -p 1555 -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -p 1555 ubuntu@${{ secrets.EC2_HOST }} "\
            cd ${{ env.PROJECT_PATH }} && \
            git fetch --all && \
            git reset --hard origin/deployment && \
            sudo docker system prune -af --volumes && \
            sudo docker compose down && \
            sudo docker compose build --no-cache && \
            sudo docker compose up -d && \
            sudo docker compose ps"