name: Deploy to AWS EC2

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection..."
          echo "Host: ${{ secrets.EC2_HOST }}"
          ssh-keyscan -v -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>&1 || echo "ssh-keyscan failed"
          
          # Test SSH connection
          ssh -v ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'echo "SSH Connection Successful"' || echo "SSH connection failed"

      - name: Copy files to EC2
        if: success()
        run: |
          echo "Starting file copy..."
          scp -v -r docker-compose.yml .env* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/Agente_Terry/ || echo "SCP failed for docker-compose and env files"
          scp -v -r * ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/Agente_Terry/ || echo "SCP failed for remaining files"

      - name: Deploy on EC2
        if: success()
        run: |
          ssh -v ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/Agente_Terry &&
            docker compose down &&
            docker compose up --build -d
          '